DROP TABLE IF EXISTS recipes;

CREATE TABLE recipes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    recipe_name TEXT NOT NULL,
    description TEXT,
    date_published TIMESTAMPTZ DEFAULT now() NOT NULL,
    author INTEGER
        REFERENCES nom_users(id) ON DELETE CASCADE NOT NULL,
    updated_on TIMESTAMPTZ DEFAULT now() NOT NULL    
);