DROP TABLE IF EXISTS noms;

CREATE TABLE noms (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nom_name TEXT NOT NULL,
    sub TEXT NOT NULL,
    url TEXT,
    description TEXT,
    recipe_id INTEGER
        REFERENCES recipes(id) ON DELETE CASCADE NOT NULL,   
    user_id INTEGER
        REFERENCES nom_users(id) ON DELETE CASCADE NOT NULL,
    date_created TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_on TIMESTAMPTZ DEFAULT now() NOT NULL
);