INSERT INTO noms (nom_name, sub, url, description)
VALUES 
    (`Ground Flax`,	`eggs`, null, `1 tbsp ground flaxseed, 3 tbsp water`),
    (`Chia Seeds`, `eggs`, null, `1 tbsp chia seeds, 1/3 cup water`),
    (`Bob's Red Mill Egg Replacer`,	`eggs`, null, `1 tbsp egg replacer, 3 tbsp water`),
    (`Banana`, `eggs`, null, `1/2 mashed banana`),
    (`Pureed Pumpkin`, `eggs`, null, `1/4 cup pureed pumpkin`),
    (`Sweet Potato`, `eggs`, null,	`1/4 cup pureed sweet potato`),
    (`Butternut Squash`, `eggs`, null, `1/4 cup pureed butternut squash`),
    (`Avocado`, `eggs`, null, `1/4 cup mashed avocado`),
    (`Chickpea Flour (Besan)`, `eggs`, null, `4 tbsp chickpea flour, 4 tbsp water`),
    (`Aquafaba (Bean Water)`, `eggs`, null, `3 tbsp aquafaba`),
    (`Nut Butter`, `eggs`, null, `3 tbsp peanut butter or any other nut butter`),
    (`Vegan Yogurt`, `eggs`, null, `1/4 cup vegan yogurt`),
    (`Silken Tofu (Blended)`, `eggs`, null, `1/4 silken tofu`),
    (`Arrowroot Powder`, `eggs`, null, `2 tbsp arrowroot, 2 tbsp water`),
    (`Potato Starch`, `eggs`, null, `2 tbsp potato starch, 2 tbsp water`),
    (`Cornstarch`, `eggs`, null, `2 tbsp cornstarch, 2 tbsp water`),
    (`Apple Cider Vinegar & Baking Soda`, `eggs`, null, `1 tbsp apple cider vinegar, 1 tsp`),
    (`Lemon Juice & Baking Soda`,`eggs`, null, `2 tbsp lemon juice, 1 tsp`),
    (`Oil, Water & Baking Soda`, `eggs`, null, `2 tbsp baking soda, 2 tbsp water, 1 tbsp oil`),
    (`Oil, Water & Baking Powder`, `eggs`, null, `2 tbsp baking powder, 2 tbsp water, 1 tbsp oil`),
    (`Applesauce`, `eggs`, null, `1/4 cup unsweetened applesauce`),
    (`Soy Protein Powder`, `eggs`, null, `1 tbsp soy protein powder, 3 tbsp water`),
    (`Agar-Agar`, `eggs`, null, `1 tbsp agar-agar, 1 tbsp water`),
    (`Carbonated Water`, `eggs`, null, null),
    (`tofu`, `meat`, null, null),
    (`seitan`, `meat`, null, null),		
    (`tempeh`, `meat`, null, null),		
    (`jackfruit`, `meat`, null, null),		
    (`Soy`, `milk`, null, null),	
    (`Hazelnut`, `milk`, null, null),		
    (`Hemp milk`, `milk`, null, null),	
    (`Almond`, `milk`, null, null),		
    (Cashew	milk),		
    (Rice	milk),		
    (Oat	milk),		
    (Flaxmilk	milk),		
    (Pea Milk	milk),		
    (Coconut	milk),		
    (cashew	yogurt),	
    (Coconut	yogurt),		
    (soy	yogurt),
    (blue agave syrup	honey),		
    (maple syrup	honey),
    (stevia	white sugar),
    (monk fruit sweetner	white sugar),		
    (vegan sugar	white sugar),
    (coconut oil	shortening),	
    (vegetable shortening	shortening),		
    (Agar-Agar	gellatin),
    (pea protein	protein powder),		
    (Stork Baking Margerine	butter),	
    (Flora Plant Butter	butter),
    (Field Roast Chao Cheese Creamy Original	cheese),		
    (Violife Mature Cheddar	cheese),
    (365 Plant-Based Cheddar	cheese),		
    (Violife Smoked Provolone	cheese),	
    (Follow Your Heart American	cheese),	
    (Follow Your Heart Provolone	cheese),		
    (Follow Your Heart Smoked Gouda	cheese),	
    (365 Plant-Based Smoked Gouda	cheese),	
    (Daiya Deliciously Dairy-Free Cheddar Style Slices	cheese),
    (Follow Your Heart Pepper Jack	cheese),
    (Treeline Soft French-Style Nut Cheese	cheese),		
    (Sprout and Kernel Herb Nut Cheese	cheese),		
    (Daiya Mozzarella Style Shreds	cheese),		
    (Follow Your Heart Vegan Parmesan Shredded	cheese),		
    (Tofutti Better Than Ricotta Cheese	cheese),		
    (Kite Hill Cream Cheese Style Spread	cheese),		
    (Thrive Market Vegan Parmesan-Style Cheese	cheese),		
    (Follow Your Heart Cheddar Shreds	cheese),		
    (Miyokos Vegan Roadhouse Cheese Spread	cheese),		
    (Heidi Ho Ne Chevre Pure Live Culture Cashew Cheese	cheese),		
    (Field Roast Chao Creamery Vegan Slices — Tomato Cayenne	cheese),
    (Miyoko's Creamery Fresh Loire Valley Cheese in Fig Leaf	cheese),	
    (Siete Dairy Free Mild Nacho Cashew Queso	cheese),
    (Feel Good Foods Queso Style Dip	cheese),
    (365 Plant-Based Mozzarella Cheese Shreds	cheese),		
    (Violife Just Like Cheddar Shreds	cheese),
    (Miyoko's Smoked Vegan Mozz	cheese),		
    (SO Delicious Mozzarella Flavored Shreds	cheese),		
    (Nuttin Ordinary Italian Herb Cashew Cheese	cheese),	
    (Fauxmaggio Pepper Jack Cultured Tree Nut Product	cheese),		
    (Kite Hill Ricotta	cheese),
    (Toffutti Plain Cream Cheese	cheese),		
    (Fauxmaggio Fauxmesan	cheese),
    (Daiya Swiss Style Slices	cheese),		
    (MozzaRisella Cheddar	cheese),
    (MozzaRisella Cremoso	cheese),	
    (MozzaRisella Classic Pizza	cheese),		
    (MozzaRisella Spreadable Classic	cheese),		
    (MozzaRisella Alternative Blue	cheese),
    (MozzaRisella Smoked	cheese),
    (MozzaRisella Classic	cheese),	
    (Go Veggie Cheddar	cheese),
    (nutritional yeast	cheese),	
    (Sophie's Kitchen Vegan Crab Cake	seafood),		
    (Good Catch Naked in Water Fish-Free Tuna	seafood),		
    (Vegan Fish Broth	seafood	https://proveg.com/recipe/vegan-fish-broth/),	
    (Tofuna Fysh Sauce	seafood),		
    (Carrot Lox	seafood	https://olivesfordinner.com/2015/03/carrot-lox.html),	
    (Crispy Filet No Fish	seafood	https://olivesfordinner.com/2020/06/crispy-filet-no-fish.html),
    (Silky Bell Pepper Sushi	seafood	https://olivesfordinner.com/2017/08/silky-bell-pepper-sushi.html),
    (Vegan Lobster Roll	seafood	https://olivesfordinner.com/2017/05/vegan-lobster-roll.html),
    (Vegan Shrimp	seafood	https://olivesfordinner.com/2017/05/vegan-shrimp.html),
    (Watermelon Tuna Poke Bowl	seafood	https://olivesfordinner.com/2016/04/watermelon-tuna-poke-bowl.html),	
    (Pasta With Seaweed-Matcha Butter And Vegan Scallops	seafood	https://olivesfordinner.com/2016/04/pasta-with-seaweed-matcha-butter-and-vegan-scallops.html),	
    (Spicy Carrot Lox And Avocado Sushi	seafood	https://olivesfordinner.com/2016/03/spicy-carrot-lox-and-avocado-sushi.html),
    (Fish and Chips With Vegan Tartar Sauce	seafood	https://www.peta.org/recipes/fish-chips-vegan-tartar-sauce/),
    (Ahimi Vegan Raw Tuna	seafood	https://oceanhuggerfoods.com/ahimi),
    (Unami Vegan Freshwater Eel	seafood, `https://oceanhuggerfoods.com/unami`, null),